apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
spec:
  selector:
    app: auth-db # 这里的app标签需要与auth-db的Pod标签匹配
  ports:
    - protocol: TCP
      port: 3306 # 数据库服务的端口，根据实际情况修改
      targetPort: 3306 # Pod中数据库容器暴露的端口，根据实际情况修改