apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: clickhouse
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clickhouse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: clickhouse
    spec:
      containers:
      - image: clickhouse/clickhouse-server:23.8
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - wget --no-verbose --tries=1 --spider 'http://localhost:8123/ping' ||
              exit 1
          failureThreshold: 5
          periodSeconds: 5
          timeoutSeconds: 5
        name: clickhouse-db
        resources:
          limits:
            cpu: 1500m
            memory: "3221225472"
          requests:
            cpu: "1"
            memory: "2147483648"
        volumeMounts:
        - mountPath: /var/lib/clickhouse
          name: clickhouse-data
        - mountPath: /var/log/clickhouse-server
          name: clickhouse-logs
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: clickhouse-data
        persistentVolumeClaim:
          claimName: clickhouse-data
      - name: clickhouse-logs
        persistentVolumeClaim:
          claimName: clickhouse-logs
status: {}
