apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9094
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_MAX_REQUEST_SIZE
          value: "1572864000"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "1572864000"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "1572864000"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: confluentinc/cp-kafka:7.5.3
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - kafka-topics --bootstrap-server kafka:29092 --list > /dev/null || exit
              1
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 10
        name: kafka
        resources:
          limits:
            cpu: 1500m
            memory: "2147483648"
          requests:
            cpu: "1"
            memory: "1073741824"
      hostname: kafka
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
