apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: log-service
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: log-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: log-service
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_URL
          value: kafka:29092
        image: log-service
        imagePullPolicy: ""
        name: frontend-log-ingestion
        resources:
          limits:
            cpu: 500m
            memory: "536870912"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
