apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: minio
    spec:
      containers:
      - args:
        - minio
        - server
        - /data
        - --console-address
        - :9001
        env:
        - name: MINIO_CORS_ALLOW_ORIGIN
          value: http://localhost:5173
        - name: MINIO_ROOT_PASSWORD
        - name: MINIO_ROOT_USER
        image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:9002/minio/health/live
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 20
        name: minio
        resources:
          limits:
            cpu: "1"
            memory: "1073741824"
          requests:
            cpu: 500m
            memory: "536870912"
        volumeMounts:
        - mountPath: /data
          name: minio-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-data
status: {}
