apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: offline-recommendation-service
  name: offline-recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: offline-recommendation-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: offline-recommendation-service
    spec:
      containers:
      - env:
        - name: REC_DB_HOST
          value: recommendation_db
        - name: REC_DB_NAME
          value: recommendation_db
        - name: REC_DB_PASSWORD
          value: rec_password
        - name: REC_DB_USER
          value: rec_user
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        image: offline-recommendation-service
        imagePullPolicy: ""
        name: offline-recommendation-service-app
        resources:
          limits:
            cpu: 500m
            memory: "536870912"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
