apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: recommendation-db
  name: recommendation-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recommendation-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: recommendation-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: recommendation_db
        - name: MYSQL_PASSWORD
          value: rec_password
        - name: MYSQL_ROOT_PASSWORD
          value: your_rec_root_password
        - name: MYSQL_USER
          value: rec_user
        image: mysql:8.0
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          failureThreshold: 10
          periodSeconds: 10
          timeoutSeconds: 20
        name: recommendation-mysql-db
        resources:
          limits:
            cpu: "1"
            memory: "1073741824"
          requests:
            cpu: 500m
            memory: "536870912"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: recommendation-mysql-data
        - mountPath: /docker-entrypoint-initdb.d/init_recommendation_db.sql
          name: recommendation-db-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: recommendation-mysql-data
        persistentVolumeClaim:
          claimName: recommendation-mysql-data
      - name: recommendation-db-claim1
        persistentVolumeClaim:
          claimName: recommendation-db-claim1
status: {}
