apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-etl-processor
  name: spark-etl-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-etl-processor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: spark-etl-processor
    spec:
      containers:
      - args:
        - /opt/bitnami/spark/bin/spark-submit
        - --master
        - local[*]
        - --driver-memory
        - 2G
        - --executor-memory
        - 2G
        - --packages
        - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.apache.kafka:kafka-clients:3.4.1,org.mongodb.spark:mongo-spark-connector_2.12:3.0.1,mysql:mysql-connector-java:8.0.28
        - /app/main.py
        env:
        - name: CLICKHOUSE_HOST
          value: clickhouse
        - name: CLICKHOUSE_PORT
          value: "8123"
        - name: KAFKA_BROKER_URL
          value: kafka:29092
        - name: REC_DB_HOST
          value: recommendation_db
        - name: REC_DB_NAME
          value: recommendation_db
        - name: REC_DB_PASSWORD
          value: rec_password
        - name: REC_DB_USER
          value: rec_user
        image: spark-etl-processor
        imagePullPolicy: ""
        name: spark-etl-processor
        resources:
          limits:
            cpu: "2"
            memory: "4294967296"
          requests:
            cpu: "1"
            memory: "2147483648"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
