apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: user-engagement-service
  name: user-engagement-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-engagement-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: user-engagement-service
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: mysql+pymysql://engagement_user:engagement_password@user_engagement_db:3306/book_engagement
        image: user-engagement-service
        imagePullPolicy: ""
        name: user-engagement-service-app
        resources:
          limits:
            cpu: 500m
            memory: "536870912"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
