apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: zookeeper
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        image: confluentinc/cp-zookeeper:7.5.3
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - nc -z localhost 2181 || exit 1
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 5
        name: zookeeper
        resources:
          limits:
            cpu: 500m
            memory: "536870912"
      hostname: zookeeper
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
