apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: book-manage
  name: book-manage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: book-manage
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: book-manage
    spec:
      containers:
      - env:
        - name: MONGO_DB_NAME
          value: book_manage_db
        - name: MONGO_HOST
          value: book_db_mongo
        - name: MONGO_PASSWORD
          value: book_password
        - name: MONGO_USER
          value: book_user
        image: book-manage
        imagePullPolicy: ""
        name: book-manage
        resources:
          limits:
            cpu: 500m
            memory: "536870912"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
