apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
      -o k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-setup
  name: mongo-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-setup
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-copy.yml
          -o k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-setup
    spec:
      containers:
      - args:
        - bash
        - -c
        - |2

            mongosh --host book_db_mongo:27017 --username book_user --password book_password --authenticationDatabase admin <<EOF
              rs.initiate({
                _id: 'dbrs',
                members: [ { _id: 0, host: 'book_db_mongo:27017' } ]
              });EOF
        image: mongo:latest
        imagePullPolicy: ""
        name: mongo-setup
        resources:
          limits:
            cpu: 200m
            memory: "268435456"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
